local _, Addon = ...

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--  Default Preperation
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local dungeonListInt = {
    [244] = 0,
    [245] = 0,
    [246] = 0,
    [247] = 0,
    [248] = 0,
    [249] = 0,
    [250] = 0,
    [251] = 0,
    [252] = 0,
    [353] = 0,
    [369] = 0,
    [370] = 0,
    [375] = 0,
    [376] = 0,
    [377] = 0,
    [378] = 0,
    [379] = 0,
    [380] = 0,
    [381] = 0,
    [382] = 0,
}
local dungeonListTable = {
    [244] = {},
    [245] = {},
    [246] = {},
    [247] = {},
    [248] = {},
    [249] = {},
    [250] = {},
    [251] = {},
    [252] = {},
    [353] = {},
    [369] = {},
    [370] = {},
    [375] = {},
    [376] = {},
    [377] = {},
    [378] = {},
    [379] = {},
    [380] = {},
    [381] = {},
    [382] = {},
}
local bestList = {
    level       = 0,
    duration    = 100000,
    date        = 0,
}
local levelBossTiming = {
    [1] = {duration = 100000},
    [2] = {duration = 100000},
    [3] = {duration = 100000},
    [4] = {duration = 100000},
    [5] = {duration = 100000},
}

local levelBossTimingBest = {
    [1]  = levelBossTiming,
    [2]  = levelBossTiming,
    [3]  = levelBossTiming,
    [4]  = levelBossTiming,
    [5]  = levelBossTiming,
    [6]  = levelBossTiming,
    [7]  = levelBossTiming,
    [8]  = levelBossTiming,
    [9]  = levelBossTiming,
    [10] = levelBossTiming,
    [11] = levelBossTiming,
    [12] = levelBossTiming,
    [13] = levelBossTiming,
    [14] = levelBossTiming,
    [15] = levelBossTiming,
    [16] = levelBossTiming,
    [17] = levelBossTiming,
    [18] = levelBossTiming,
    [19] = levelBossTiming,
    [20] = levelBossTiming,
    [21] = levelBossTiming,
    [22] = levelBossTiming,
    [23] = levelBossTiming,
    [24] = levelBossTiming,
    [25] = levelBossTiming,
    [26] = levelBossTiming,
    [27] = levelBossTiming,
    [28] = levelBossTiming,
    [29] = levelBossTiming,
    [30] = levelBossTiming,
    [31] = levelBossTiming,
    [32] = levelBossTiming,
    [33] = levelBossTiming,
    [34] = levelBossTiming,
    [35] = levelBossTiming,
}
local dungeonBestBossT = {
    [244] = levelBossTimingBest,
    [245] = levelBossTimingBest,
    [246] = levelBossTimingBest,
    [247] = levelBossTimingBest,
    [248] = levelBossTimingBest,
    [249] = levelBossTimingBest,
    [250] = levelBossTimingBest,
    [251] = levelBossTimingBest,
    [252] = levelBossTimingBest,
    [353] = levelBossTimingBest,
    [369] = levelBossTimingBest,
    [370] = levelBossTimingBest,
    [375] = levelBossTimingBest,
    [376] = levelBossTimingBest,
    [377] = levelBossTimingBest,
    [378] = levelBossTimingBest,
    [379] = levelBossTimingBest,
    [380] = levelBossTimingBest,
    [381] = levelBossTimingBest,
    [382] = levelBossTimingBest,
}
local dungeonListTableBest = {
    [244] = bestList,
    [245] = bestList,
    [246] = bestList,
    [247] = bestList,
    [248] = bestList,
    [249] = bestList,
    [250] = bestList,
    [251] = bestList,
    [252] = bestList,
    [353] = bestList,
    [369] = bestList,
    [370] = bestList,
    [375] = bestList,
    [376] = bestList,
    [377] = bestList,
    [378] = bestList,
    [379] = bestList,
    [380] = bestList,
    [381] = bestList,
    [382] = bestList,
}
local bestListTable = {
    level           = {},
    duration        = {},
    durationTrans   = {},
    date            = {},
}
local historyListTableBest = {
    [244] = bestListTable,
    [245] = bestListTable,
    [246] = bestListTable,
    [247] = bestListTable,
    [248] = bestListTable,
    [249] = bestListTable,
    [250] = bestListTable,
    [251] = bestListTable,
    [252] = bestListTable,
    [353] = bestListTable,
    [369] = bestListTable,
    [370] = bestListTable,
    [375] = bestListTable,
    [376] = bestListTable,
    [377] = bestListTable,
    [378] = bestListTable,
    [379] = bestListTable,
    [380] = bestListTable,
    [381] = bestListTable,
    [382] = bestListTable,
}
local statDB = {
    deaths = 0,
    volcanic = 0,
    pride = 0,
}

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--  Actual Defaults
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Addon.GlobalDefaults = {
    --global defaults
    statistic = statDB,
}

Addon.ProfileDefaults = {
    --character defaults
    statistic       = statDB,
    colorit         = {
                        r = 0,
                        g = 0.7,
                        b = 0.5,
                        a = 0.8,
                        hex = "00b380",
                    },
    customKeyColor  = {
                        r = 1,
                        g = 1,
                        b = 1,
                        a = 1,
                        hex = "ffffff",
                    },
    timerBarColor   = {
                        r = 0,
                        g = 0.7,
                        b = 1,
                        a = 1,
                        hex = "00b3ff",
                    },
    mobBarColor     = {
                        r = 0.5,
                        g = 1,
                        b = 0,
                        a = 1,
                        hex = "80ff00",
                    },
    tormentedColor  = {
                        r = 0.3,
                        g = 1,
                        b = 0.5,
                        a = 1,
                        hex = "57ff79",
                    },
    timeStamp       = true,
    keyColor        = true,
    plusOne         = true,
    plusTwo         = true,
    plusThree       = true,
    smartTimer      = false,
    history         = true,
    autoPlace       = true,
    unlock          = false,
    pridefulAlertT  = true,
    postCom         = false,
    postComCov      = true,
    autoPost        = false,
    autoRole        = false,
    start           = false,
    invertPerc      = false,
    MobPercStep     = true,
    SendMSGEnable   = false,
    SendMSGLevel    = true,
    SendMSGName     = true,
    SendMSGTime     = true,
    SendMSGForces   = true,
    SendMSGBosses   = true,
    SendMSGDeaths   = true,
    devtools        = false,
    Changed         = false,
    Minimap         = true,
    ShareTotal      = true,
    tormentedInd    = true,
    background      = 2,
    sparkle         = 3,
    bosses          = 3,
    affix           = 1,
    dungeonName     = 1,
    mainTimer       = 1,
    mobCount        = 1,
    MobPullConf     = 3,
    bestBefore      = 4,
    ScaleStyle      = 1,
    SendMSGDelay    = 5,
    DateFormat      = 1,
    DateFormatSep   = 1,
    tormentedStyle  = 1,
    fpoint          = "TOPRIGHT",
    TimerBarStyle   = "Lucid Keystone Particles",
    MobBarStyle     = "Lucid Keystone Particles",
    FontStyle       = "Kozuka Gothic Light",
    pridefulAlertSound = "Stop Death",
    importFrom      = "",
    fxof            = -140,
    fyof            = 0,
    expansion       = GetExpansionLevel(),
    season          = 2,
    dungeonBestBoss = dungeonBestBossT,
    KeyComm         = {},
    runs            = {
                        [7] = { --expansion
                            [1] = { -- season
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                            [2] = {
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                            [3] = {
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                            [4] = {
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                        },
                        [8] = { --expansion
                            [1] = { -- season
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                            [2] = {
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                            [3] = {
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                            [4] = {
                                [1] = dungeonListInt,
                                [2] = dungeonListInt,
                            },
                        },
                    },
    avglvl          = {
                        [7] = { --expansion
                            [1] = { -- season
                                [1] = dungeonListTable,
                            },
                            [2] = {
                                [1] = dungeonListTable,
                            },
                            [3] = {
                                [1] = dungeonListTable,
                            },
                            [4] = {
                                [1] = dungeonListTable,
                            },
                        },
                        [8] = { --expansion
                            [1] = { -- season
                                [1] = dungeonListTable,
                            },
                            [2] = {
                                [1] = dungeonListTable,
                            },
                            [3] = {
                                [1] = dungeonListTable,
                            },
                            [4] = {
                                [1] = dungeonListTable,
                            },
                        },
                    },
    bestIntime      = {
                        [7] = {
                            [1] = dungeonListTableBest,
                            [2] = dungeonListTableBest,
                            [3] = dungeonListTableBest,
                            [4] = dungeonListTableBest,
                        },
                        [8] = {
                            [1] = dungeonListTableBest,
                            [2] = dungeonListTableBest,
                            [3] = dungeonListTableBest,
                            [4] = dungeonListTableBest,
                        },
                    },
    bestOvertime    = {
                        [7] = {
                            [1] = dungeonListTableBest,
                            [2] = dungeonListTableBest,
                            [3] = dungeonListTableBest,
                            [4] = dungeonListTableBest,
                        },
                        [8] = {
                            [1] = dungeonListTableBest,
                            [2] = dungeonListTableBest,
                            [3] = dungeonListTableBest,
                            [4] = dungeonListTableBest,
                        },
                    },
    dungeonHistory  = {
                        [7] = {
                            [1] = historyListTableBest,
                            [2] = historyListTableBest,
                            [3] = historyListTableBest,
                            [4] = historyListTableBest,
                        },
                        [8] = {
                            [1] = historyListTableBest,
                            [2] = historyListTableBest,
                            [3] = historyListTableBest,
                            [4] = historyListTableBest,
                        },
                    },
}